name: ⚙️ Build Binaries

on:
  workflow_call:

env:
  APP_NAME: tsm
  NIM_VERSION: stable
  RELEASE_FILES: tsm

jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          # - windows-latest # tmux isn't on windows

    steps:
      - uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}

      - run: nimble build -Y -d:release

      - name: Create artifact
        run: |
          assets="${{ env.APP_NAME }}_$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')"
          echo "$assets"
          mkdir -p "dist/$assets"
          cp -r ${{ env.RELEASE_FILES }} "dist/$assets/"
          (
            cd dist
            if [[ "${{ runner.os }}" == Windows ]]; then
              7z a "$assets.zip" "$assets"
            else
              tar czf "$assets.tar.gz" "$assets"
            fi
            ls -lah *.*
          )

      - uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.os }}
          path: |
            dist/*.tar.gz
            dist/*.zip

